-- public.document_master_no_auth definition

-- Drop table

-- DROP TABLE public.document_master_no_auth; 

--CREATE TABLE public.document_master_no_auth (
--	doc_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
--	doc_type int4 NULL,
--	doc_name varchar(255) NULL,
--	doc_desc varchar(255) NULL,
--	doc_abbr varchar(255) NULL,
--	doc_path varchar(255) NULL,
--	doc_location varchar(100) NULL,
--	created_on timestamptz NULL,
--	updated_on timestamptz NULL,
--	status int2 NULL,
--	CONSTRAINT document_master_no_auth_pkey PRIMARY KEY (doc_id)
--);	

--ALTER TABLE document_master_no_auth ADD COLUMN doc_file_type varchar(255);

SELECT 
    t.relname AS table_name,
    l.locktype,
    l.mode,
    l.granted,
    a.usename AS user_name,
    a.query,
    a.state,
    a.query_start,
    a.pid
FROM pg_locks l
JOIN pg_stat_activity a ON l.pid = a.pid
JOIN pg_class t ON l.relation = t.oid
WHERE t.relkind = 'r' -- only regular tables
  AND l.mode NOT IN ('AccessShareLock') -- exclude non-conflicting read locks
ORDER BY a.query_start;



select count(1) from pg_stat_activity;
