-- DROP PROCEDURE public.run_partition_migration();

CREATE OR REPLACE PROCEDURE public.run_partition_migration()
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    i INT;
    v_owner TEXT;
BEGIN

-- =====================================================
-- CLEAN OLD BACKUP TABLES
-- =====================================================
DROP TABLE IF EXISTS citizen_old CASCADE;
DROP TABLE IF EXISTS citizen_address_old CASCADE;
DROP TABLE IF EXISTS service_request_old CASCADE;
DROP TABLE IF EXISTS service_request_lifecycle_old CASCADE;
DROP TABLE IF EXISTS service_review_old CASCADE;


-- =====================================================
-- CITIZEN
-- =====================================================
SELECT pg_get_userbyid(relowner)
INTO v_owner
FROM pg_class
WHERE relname = 'citizen'
AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

DROP TABLE IF EXISTS citizen_new CASCADE;

--CREATE TABLE citizen_new
--(LIKE citizen INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES)
--PARTITION BY HASH (id);

CREATE TABLE citizen_new (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	first_name varchar(50) NULL,
	middle_name varchar(50) NULL,
	last_name varchar(50) NULL,
	gender varchar(50) NULL,
	date_of_birth date NULL,
	mobile_number varchar(15) NULL,
	email varchar(100) NULL,
	status int2 NULL,
	created_by int4 NULL,
	created_on timestamptz NULL,
	updated_by int4 NULL,
	updated_on timestamptz NULL,
	block_id int4 NULL,
	district_id int4 NULL,
	state_id int4 NULL,
	user_type int4 NULL,
	alter_number varchar(15) NULL,
	CONSTRAINT citizen_new_pkey PRIMARY KEY (id)
)
PARTITION BY HASH (id);

FOR i IN 0..49 LOOP
    EXECUTE format(
        'CREATE TABLE citizen_p%s PARTITION OF citizen_new
         FOR VALUES WITH (MODULUS 50, REMAINDER %s)',
        i,i
    );
END LOOP;

INSERT INTO citizen_new SELECT * FROM citizen;

ALTER TABLE citizen RENAME TO citizen_old;
ALTER TABLE citizen_new RENAME TO citizen;

EXECUTE format('ALTER TABLE citizen OWNER TO %I', v_owner);

DROP TABLE citizen_old CASCADE;


-- =====================================================
-- CITIZEN ADDRESS
-- =====================================================
SELECT pg_get_userbyid(relowner)
INTO v_owner
FROM pg_class
WHERE relname = 'citizen_address'
AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

DROP TABLE IF EXISTS citizen_address_new CASCADE;

--CREATE TABLE citizen_address_new
--(LIKE citizen_address INCLUDING DEFAULTS INCLUDING INDEXES)
--PARTITION BY HASH (citizen_id);

CREATE TABLE citizen_address_new (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	address_line_1 varchar(100) NULL,
	address_line_2 varchar(100) NULL,
	land_mark varchar(50) NULL,
	city varchar(50) NULL,
	district_id int4 NULL,
	state varchar(50) NULL,
	country varchar(50) NULL,
	pincode varchar(50) NULL,
	lattitude varchar(50) NULL,
	longitude varchar(50) NULL,
	is_primary bool NOT NULL,
	status int2 NULL,
	created_by int4 NULL,
	created_on timestamptz NULL,
	updated_by int4 NULL,
	updated_on timestamptz NULL,
	citizen_id int4 NOT NULL,
	CONSTRAINT citizen_address_new_pkey PRIMARY KEY (id, citizen_id)
)
PARTITION BY HASH (citizen_id);

FOR i IN 0..49 LOOP
    EXECUTE format(
        'CREATE TABLE citizen_address_p%s PARTITION OF citizen_address_new
         FOR VALUES WITH (MODULUS 50, REMAINDER %s)',
        i,i
    );
END LOOP;

INSERT INTO citizen_address_new SELECT * FROM citizen_address;

ALTER TABLE citizen_address RENAME TO citizen_address_old;
ALTER TABLE citizen_address_new RENAME TO citizen_address;

EXECUTE format('ALTER TABLE citizen_address OWNER TO %I', v_owner);

DROP TABLE citizen_address_old CASCADE;


-- =====================================================
-- SERVICE REQUEST
-- =====================================================
SELECT pg_get_userbyid(relowner)
INTO v_owner
FROM pg_class
WHERE relname = 'service_request'
AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

DROP TABLE IF EXISTS service_request_new CASCADE;

--CREATE TABLE service_request_new
--(LIKE service_request INCLUDING DEFAULTS INCLUDING INDEXES)
--PARTITION BY HASH (citizen_id);

CREATE TABLE service_request_new (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	status int2 NULL,
	created_by int8 NULL,
	created_on timestamptz NULL,
	updated_by int8 NULL,
	updated_on timestamptz NULL,
	block_id int4 NULL,
	citizen_id int4 NOT NULL,
	district_id int4 NOT NULL,
	sector_id int4 NOT NULL,
	service_id int8 NOT NULL,
	skill_id int4 NOT NULL,
	is_active bool NOT NULL,
	assigned_by int8 NULL,
	assigned_on timestamptz NULL,
	assigned_to int8 NULL,
	service_code varchar(50) NULL,
	service_desc varchar(1000) NULL,
	address_id int4 NULL,
	preferred_day int2 NULL,
	preferred_date date NULL,
	end_time time NULL,
	start_time time NULL,
	booking_code varchar(10) NULL,
	candidate_id int4 NULL,
	CONSTRAINT service_request_new_pkey PRIMARY KEY (id, citizen_id)
)
PARTITION BY HASH (citizen_id);

FOR i IN 0..49 LOOP
    EXECUTE format(
        'CREATE TABLE service_request_p%s PARTITION OF service_request_new
         FOR VALUES WITH (MODULUS 50, REMAINDER %s)',
        i,i
    );
END LOOP;

INSERT INTO service_request_new SELECT * FROM service_request;

ALTER TABLE service_request RENAME TO service_request_old;
ALTER TABLE service_request_new RENAME TO service_request;

EXECUTE format('ALTER TABLE service_request OWNER TO %I', v_owner);

DROP TABLE service_request_old CASCADE;



-- =====================================================
-- SERVICE REQUEST LIFECYCLE
-- =====================================================
SELECT pg_get_userbyid(relowner)
INTO v_owner
FROM pg_class
WHERE relname = 'service_request_lifecycle'
AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

DROP TABLE IF EXISTS service_request_lifecycle_new CASCADE;

--CREATE TABLE service_request_lifecycle_new
--(LIKE service_request_lifecycle INCLUDING DEFAULTS INCLUDING INDEXES)
--PARTITION BY HASH (citizen_id);

CREATE TABLE service_request_lifecycle_new (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	lifecycle_status int2 NULL,
	created_by int8 NULL,
	created_on timestamptz NULL,
	updated_by int8 NULL,
	updated_on timestamptz NULL,
	remarks varchar(255) NULL,
	candidate_id int4 NOT NULL,
	citizen_id int4 NOT NULL,
	service_id int8 NOT NULL,
	service_request_id int8 NOT NULL,
	assigned_by int8 NULL,
	assigned_on timestamptz NULL,
	assigned_to int8 NULL,
	service_desc varchar(1000) NULL,
	CONSTRAINT service_request_lifecycle_new_pkey PRIMARY KEY (id, citizen_id)
)
PARTITION BY HASH (citizen_id);

FOR i IN 0..49 LOOP
    EXECUTE format(
        'CREATE TABLE service_request_lifecycle_p%s
         PARTITION OF service_request_lifecycle_new
         FOR VALUES WITH (MODULUS 50, REMAINDER %s)',
        i,i
    );
END LOOP;

INSERT INTO service_request_lifecycle_new
SELECT * FROM service_request_lifecycle;

ALTER TABLE service_request_lifecycle RENAME TO service_request_lifecycle_old;
ALTER TABLE service_request_lifecycle_new RENAME TO service_request_lifecycle;

EXECUTE format('ALTER TABLE service_request_lifecycle OWNER TO %I', v_owner);

DROP TABLE service_request_lifecycle_old CASCADE;



-- =====================================================
-- SERVICE REVIEW
-- =====================================================
SELECT pg_get_userbyid(relowner)
INTO v_owner
FROM pg_class
WHERE relname = 'service_review'
AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

DROP TABLE IF EXISTS service_review_new CASCADE;

--CREATE TABLE service_review_new
--(LIKE service_review INCLUDING DEFAULTS INCLUDING INDEXES)
--PARTITION BY HASH (citizen_id);

CREATE TABLE service_review_new (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ratings int2 NULL,
	remarks varchar(500) NULL,
	created_by int8 NULL,
	created_on timestamptz NULL,
	updated_by int8 NULL,
	updated_on timestamptz NULL,
	candidate_id int4 NOT NULL,
	citizen_id int4 NOT NULL,
	request_id int8 NOT NULL,
	is_citizen_ratted bool NOT NULL,
	is_gig_ratted bool NOT NULL,
	CONSTRAINT service_review_new_pkey PRIMARY KEY (id, citizen_id)
)
PARTITION BY HASH (citizen_id);

FOR i IN 0..49 LOOP
    EXECUTE format(
        'CREATE TABLE service_review_p%s
         PARTITION OF service_review_new
         FOR VALUES WITH (MODULUS 50, REMAINDER %s)',
        i,i
    );
END LOOP;

INSERT INTO service_review_new SELECT * FROM service_review;

ALTER TABLE service_review RENAME TO service_review_old;
ALTER TABLE service_review_new RENAME TO service_review;

EXECUTE format('ALTER TABLE service_review OWNER TO %I', v_owner);

DROP TABLE service_review_old CASCADE;



-- =====================================================
-- INDEXES
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_citizen_mobile_number
ON citizen(mobile_number);

CREATE INDEX IF NOT EXISTS idx_citizen_created_on
ON citizen(created_on);

CREATE INDEX IF NOT EXISTS idx_citizen_address_citizen_id
ON citizen_address(citizen_id);

CREATE INDEX IF NOT EXISTS idx_citizen_address_district_id
ON citizen_address(district_id);

CREATE INDEX IF NOT EXISTS idx_service_review_candidate_id
ON service_review(candidate_id);

CREATE INDEX IF NOT EXISTS idx_service_review_request_id
ON service_review(request_id);

CREATE INDEX IF NOT EXISTS idx_service_request_candidate_id
ON service_request(candidate_id);

CREATE INDEX IF NOT EXISTS idx_service_request_service_id
ON service_request(service_id);

CREATE INDEX IF NOT EXISTS idx_service_request_skill_id
ON service_request(skill_id);

CREATE INDEX IF NOT EXISTS idx_service_request_lifecycle_candidate
ON service_request_lifecycle(candidate_id);


-- ==========================================================
-- RESTORE IDENTITY COLUMNS (SAFE)
-- ==========================================================
BEGIN
ALTER TABLE citizen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN duplicate_object THEN END;

BEGIN
ALTER TABLE citizen_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN duplicate_object THEN END;

BEGIN
ALTER TABLE service_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN duplicate_object THEN END;

BEGIN
ALTER TABLE service_request_lifecycle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN duplicate_object THEN END;

BEGIN
ALTER TABLE service_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN duplicate_object THEN END;



-- ==========================================================
-- RESET SEQUENCES
-- ==========================================================
PERFORM setval(pg_get_serial_sequence('public.citizen','id'),
COALESCE((SELECT MAX(id) FROM citizen),1), true);

PERFORM setval(pg_get_serial_sequence('public.citizen_address','id'),
COALESCE((SELECT MAX(id) FROM citizen_address),1), true);

PERFORM setval(pg_get_serial_sequence('public.service_request','id'),
COALESCE((SELECT MAX(id) FROM service_request),1), true);

PERFORM setval(pg_get_serial_sequence('public.service_request_lifecycle','id'),
COALESCE((SELECT MAX(id) FROM service_request_lifecycle),1), true);

PERFORM setval(pg_get_serial_sequence('public.service_review','id'),
COALESCE((SELECT MAX(id) FROM service_review),1), true);

END;
$procedure$
;