CREATE TABLE public.jai_bangla_atr_push (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	atr_obj jsonb NULL,
	grievance_id int8 NULL,
	processing_status bool DEFAULT false NOT NULL,
	created_on timestamptz DEFAULT now() NOT NULL,
	created_by int8 NULL,
	updated_on timestamptz NULL,
	updated_by int8 NULL,
	CONSTRAINT jai_bangla_atr_push_pkey PRIMARY KEY (id)
);