-- public.atr_latest_4_11_bh_mat_2 source

CREATE MATERIALIZED VIEW public.atr_latest_4_11_bh_mat_2
TABLESPACE pg_default
AS WITH latest_4 AS (
         SELECT a.grievance_id,
            a.assigned_on
           FROM ( SELECT row_number() OVER (PARTITION BY gl.grievance_id ORDER BY gl.assigned_on DESC) AS rnn,
                    gl.grievance_id,
                    gl.assigned_on
                   FROM grievance_lifecycle gl
                  WHERE gl.grievance_status = 4) a
          WHERE a.rnn = 1
        ), latest_11 AS (
         SELECT a.rnn,
            a.lifecycle_id,
            a.comment,
            a.grievance_status,
            a.assigned_on,
            a.assigned_by_id,
            a.assign_comment,
            a.assigned_to_id,
            a.assign_reply,
            a.accepted_on,
            a.atr_type,
            a.atr_proposed_date,
            a.official_code,
            a.action_taken_note,
            a.atn_id,
            a.atn_reason_master_id,
            a.action_proposed,
            a.contact_date,
            a.tentative_date,
            a.prev_recv_date,
            a.prev_atr_date,
            a.closure_reason_id,
            a.atr_submit_on,
            a.created_by,
            a.created_on,
            a.grievance_id,
            a.assigned_by_position,
            a.assigned_to_position,
            a.urgency_type,
            a.addl_doc_id,
            a.current_atr_date,
            a.atr_doc_id,
            a.assigned_by_office_id,
            a.assigned_to_office_id,
            a.assigned_by_office_cat,
            a.assigned_to_office_cat,
            a.migration_id,
            a.migration_id_ac_tkn
           FROM ( SELECT row_number() OVER (PARTITION BY gl.grievance_id ORDER BY gl.assigned_on DESC) AS rnn,
                    gl.lifecycle_id,
                    gl.comment,
                    gl.grievance_status,
                    gl.assigned_on,
                    gl.assigned_by_id,
                    gl.assign_comment,
                    gl.assigned_to_id,
                    gl.assign_reply,
                    gl.accepted_on,
                    gl.atr_type,
                    gl.atr_proposed_date,
                    gl.official_code,
                    gl.action_taken_note,
                    gl.atn_id,
                    gl.atn_reason_master_id,
                    gl.action_proposed,
                    gl.contact_date,
                    gl.tentative_date,
                    gl.prev_recv_date,
                    gl.prev_atr_date,
                    gl.closure_reason_id,
                    gl.atr_submit_on,
                    gl.created_by,
                    gl.created_on,
                    gl.grievance_id,
                    gl.assigned_by_position,
                    gl.assigned_to_position,
                    gl.urgency_type,
                    gl.addl_doc_id,
                    gl.current_atr_date,
                    gl.atr_doc_id,
                    gl.assigned_by_office_id,
                    gl.assigned_to_office_id,
                    gl.assigned_by_office_cat,
                    gl.assigned_to_office_cat,
                    gl.migration_id,
                    gl.migration_id_ac_tkn
                   FROM grievance_lifecycle gl
                  WHERE gl.grievance_status = 11) a
             JOIN latest_4 ON latest_4.grievance_id = a.grievance_id
          WHERE a.rnn = 1 AND latest_4.assigned_on < a.assigned_on
        )
 SELECT cmo_police_station_master.sub_district_id,
    grievance_master.district_id,
    grievance_master.block_id,
    grievance_master.municipality_id,
    grievance_master.gp_id,
    grievance_master.ward_id,
    grievance_master.police_station_id,
    grievance_master.assembly_const_id,
    grievance_master.postoffice_id,
    grievance_master.grievance_category,
    grievance_master.sub_division_id,
    grievance_master.status AS current_status,
    grievance_master.grievance_source,
    grievance_master.closure_reason_id AS grievance_master_closure_reason_id,
    grievance_master.grievance_generate_date,
    grievance_master.applicant_gender,
    grievance_master.applicant_caste,
    grievance_master.applicant_reigion,
    grievance_master.applicant_age,
    grievance_master.atr_submit_by_lastest_office_id,
    grievance_master.receipt_mode,
    grievance_master.received_at,
    latest_11.rnn,
    latest_11.lifecycle_id,
    latest_11.comment,
    latest_11.grievance_status,
    latest_11.assigned_on,
    latest_11.assigned_by_id,
    latest_11.assign_comment,
    latest_11.assigned_to_id,
    latest_11.assign_reply,
    latest_11.accepted_on,
    latest_11.atr_type,
    latest_11.atr_proposed_date,
    latest_11.official_code,
    latest_11.action_taken_note,
    latest_11.atn_id,
    latest_11.atn_reason_master_id,
    latest_11.action_proposed,
    latest_11.contact_date,
    latest_11.tentative_date,
    latest_11.prev_recv_date,
    latest_11.prev_atr_date,
    latest_11.closure_reason_id,
    latest_11.atr_submit_on,
    latest_11.created_by,
    latest_11.created_on,
    latest_11.grievance_id,
    latest_11.assigned_by_position,
    latest_11.assigned_to_position,
    latest_11.urgency_type,
    latest_11.addl_doc_id,
    latest_11.current_atr_date,
    latest_11.atr_doc_id,
    latest_11.assigned_by_office_id,
    latest_11.assigned_to_office_id,
    latest_11.assigned_by_office_cat,
    latest_11.assigned_to_office_cat,
    latest_11.migration_id,
    latest_11.migration_id_ac_tkn
   FROM latest_11
     JOIN grievance_master ON latest_11.grievance_id = grievance_master.grievance_id
     LEFT JOIN cmo_police_station_master ON cmo_police_station_master.ps_id = grievance_master.police_station_id
WITH DATA;





-----------------------------------------------------------------------------------------------------
WITH latest_4 AS (
         	SELECT *
--				a.rnn,
--            a.lifecycle_id,
--            a.comment,
--            a.grievance_status,
--            a.assigned_on,
--            a.assigned_by_id,
--            a.assign_comment,
--            a.assigned_to_id,
--            a.assign_reply,
--            a.accepted_on,
--            a.atr_type,
--            a.atr_proposed_date,
--            a.official_code,
--            a.action_taken_note,
--            a.atn_id,
--            a.atn_reason_master_id,
--            a.action_proposed,
--            a.contact_date,
--            a.tentative_date,
--            a.prev_recv_date,
--            a.prev_atr_date,
--            a.closure_reason_id,
--            a.atr_submit_on,
--            a.created_by,
--            a.created_on,
--            a.grievance_id,
--            a.assigned_by_position,
--            a.assigned_to_position,
--            a.urgency_type,
--            a.addl_doc_id,
--            a.current_atr_date,
--            a.atr_doc_id,
--            a.assigned_by_office_id,
--            a.assigned_to_office_id,
--            a.assigned_by_office_cat,
--            a.assigned_to_office_cat,
--            a.migration_id,
--            a.migration_id_ac_tkn
           FROM ( SELECT row_number() OVER (PARTITION BY gl.grievance_id ORDER BY gl.assigned_on DESC) AS rnn, *
--                    gl.lifecycle_id,
--                    gl.comment,
--                    gl.grievance_status,
--                    gl.assigned_on,
--                    gl.assigned_by_id,
--                    gl.assign_comment,
--                    gl.assigned_to_id,
--                    gl.assign_reply,
--                    gl.accepted_on,
--                    gl.atr_type,
--                    gl.atr_proposed_date,
--                    gl.official_code,
--                    gl.action_taken_note,
--                    gl.atn_id,
--                    gl.atn_reason_master_id,
--                    gl.action_proposed,
--                    gl.contact_date,
--                    gl.tentative_date,
--                    gl.prev_recv_date,
--                    gl.prev_atr_date,
--                    gl.closure_reason_id,
--                    gl.atr_submit_on,
--                    gl.created_by,
--                    gl.created_on,
--                    gl.grievance_id,
--                    gl.assigned_by_position,
--                    gl.assigned_to_position,
--                    gl.urgency_type,
--                    gl.addl_doc_id,
--                    gl.current_atr_date,
--                    gl.atr_doc_id,
--                    gl.assigned_by_office_id,
--                    gl.assigned_to_office_id,
--                    gl.assigned_by_office_cat,
--                    gl.assigned_to_office_cat,
--                    gl.migration_id,
--                    gl.migration_id_ac_tkn
                   FROM grievance_lifecycle gl
                  WHERE gl.grievance_status = 4) a
          WHERE a.rnn = 1
        )
 SELECT count(*)
--		cmo_police_station_master.sub_district_id,
--    grievance_master.district_id,
--    grievance_master.block_id,
--    grievance_master.municipality_id,
--    grievance_master.gp_id,
--    grievance_master.ward_id,
--    grievance_master.police_station_id,
--    grievance_master.assembly_const_id,
--    grievance_master.postoffice_id,
--    grievance_master.grievance_category,
--    grievance_master.sub_division_id,
--    grievance_master.status AS current_status,
--    grievance_master.closure_reason_id AS grievance_master_closure_reason_id,
--    grievance_master.grievance_source,
--    grievance_master.grievance_generate_date,
--    grievance_master.applicant_gender,
--    grievance_master.applicant_caste,
--    grievance_master.applicant_reigion,
--    grievance_master.applicant_age,
--    grievance_master.emergency_flag,
--    grievance_master.receipt_mode,
--    grievance_master.received_at,
--    latest_4.rnn,
--    latest_4.lifecycle_id,
--    latest_4.comment,
--    latest_4.grievance_status,
--    latest_4.assigned_on,
--    latest_4.assigned_by_id,
--    latest_4.assign_comment,
--    latest_4.assigned_to_id,
--    latest_4.assign_reply,
--    latest_4.accepted_on,
--    latest_4.atr_type,
--    latest_4.atr_proposed_date,
--    latest_4.official_code,
--    latest_4.action_taken_note,
--    latest_4.atn_id,
--    latest_4.atn_reason_master_id,
--    latest_4.action_proposed,
--    latest_4.contact_date,
--    latest_4.tentative_date,
--    latest_4.prev_recv_date,
--    latest_4.prev_atr_date,
--    latest_4.closure_reason_id,
--    latest_4.atr_submit_on,
--    latest_4.created_by,
--    latest_4.created_on,
--    latest_4.grievance_id,
--    latest_4.assigned_by_position,
--    latest_4.assigned_to_position,
--    latest_4.urgency_type,
--    latest_4.addl_doc_id,
--    latest_4.current_atr_date,
--    latest_4.atr_doc_id,
--    latest_4.assigned_by_office_id,
--    latest_4.assigned_to_office_id,
--    latest_4.assigned_by_office_cat,
--    latest_4.assigned_to_office_cat,
--    latest_4.migration_id,
--    latest_4.migration_id_ac_tkn
   FROM latest_4
    JOIN grievance_master ON latest_4.grievance_id = grievance_master.grievance_id
    LEFT JOIN cmo_police_station_master ON cmo_police_station_master.ps_id = grievance_master.police_station_id
    left join admin_position_master apm on apm.position_id = latest_4.assigned_to_position
	left join admin_user_role_master aurm on aurm.role_master_id = apm.role_master_id and aurm.role_master_id in (6)